fmmdemo/fmm/urls.py
from django.conf.urls import url

from . import views
app_name = 'fmm'
urlpatterns = [
    url('^$', views.index, name='index'),
    url('^(?P<group_number>[0-9]+)/$', views.GroupFunctionList.as_view(), name='group_list'),
    url('^(?P<group_number>[0-9]+)/(?P<function_number>[0-9]+)/$', views.FunctionFeatureList.as_view(), name='function_list'),
    url('^groups', views.GroupList.as_view()),
    url('^functions', views.FunctionList.as_view()),
    url('^testfeatures2', views.TestFeatureList2.as_view()),
    url('^features', views.FeatureList.as_view()),
    url('^dependency', views.DependencyList.as_view()),
    url('^loadfmm', views.loadfmm, name='loadfmm'),
    url('^yourname',views.get_name, name='getname'),
    url('^test', views.test, name='test'),
    url(r'^feature/(?P<feature_number>[0-9]+)/$', views.edit_feature, name="edit_feature"),
    url(r'^fmm_main/$', views.fmm_main_index, name="main_index"),
    url(r'^fmm_main/(?P<group_number>[0-9]+)/$', views.fmm_main, name="fmm_main"),
]

fmmdemo/fmmdemo/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fmm/', include('fmm.urls')),
]

fmmdemo/fmm/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm

# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name


class Function(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name


class Feature(models.Model):
    CHOICE = u'CHO'
    SELECTION = u'SEL'
    RULE_TYPES = ((CHOICE, u'choice'), (SELECTION, u'selection'))
    function = models.ForeignKey(Function, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True)
    selection_name = models.CharField(max_length=100, blank=True)
    rule_type = models.CharField(max_length=15, blank=True, choices=RULE_TYPES)
    option_min = models.IntegerField(blank=True, null=True)
    option_max = models.IntegerField(blank=True, null=True)
    enabled = models.NullBooleanField(default=False)
    selected = models.NullBooleanField(default=False)

    def __str__(self):
        return self.name


class Dependency(models.Model):
    feature = models.ForeignKey(Feature, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.name

class FeatureForm(ModelForm):
    class Meta:
        model = Feature
        fields = ['name','enabled','selected']


class TestFeature(models.Model):
    # 0-Group, 1-Function, 2-Feature_Name, 3-Feature='name', 4-Dependency, 5-Rule, 6-Min, 7-Max
    CHOICE = u'CHO'
    SELECTION = u'SEL'
    RULE_TYPES = ((CHOICE, u'choice'), (SELECTION, u'selection'))
    group = models.CharField(max_length=50, blank=True)
    function = models.CharField(max_length=50, blank=True)
    feature_name = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=50, blank=True) # keyword or feature
    dependency = models.CharField(max_length=100, blank=True)
    rule_type = models.CharField(max_length=15, blank=True, choices=RULE_TYPES)
    option_min = models.IntegerField(blank=True, null=True)
    option_max = models.IntegerField(blank=True, null=True)
    enabled = models.NullBooleanField(default=False)
    selected = models.NullBooleanField(default=False)

    def __str__(self):
        return self.name


class TestFeature2(models.Model):
    # 0-Group, 1-Function, 2-Feature_Name, 3-Feature='name', 4-Dependency, 5-Rule, 6-Min, 7-Max
    CHOICE = u'CHO'
    SELECTION = u'SEL'
    RULE_TYPES = ((CHOICE, u'choice'), (SELECTION, u'selection'))
    group = models.CharField(max_length=50, blank=True)
    function = models.CharField(max_length=50, blank=True)
    feature_name = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=50, blank=True) # keyword or feature
    rule_type = models.CharField(max_length=15, blank=True, choices=RULE_TYPES)
    option_min = models.IntegerField(blank=True, null=True)
    option_max = models.IntegerField(blank=True, null=True)
    enabled = models.NullBooleanField(default=False)
    selected = models.NullBooleanField(default=False)

    def __str__(self):
        return self.name


class TestDependency2(models.Model):
    name = models.CharField(max_length=100, blank=True)
    feature = models.ForeignKey(TestFeature2, on_delete=models.CASCADE)

fmmdemo/fmm/forms.py
from django import forms
from fmm.models import Feature

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

class FeatureForm(forms.ModelForm):
    class Meta:
        model = Feature
        fields = ['enabled', 'selected']

fmmdemo/fmm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView
from django.shortcuts import get_object_or_404

from .models import Group, Function, Feature, Dependency, TestFeature, TestFeature2, TestDependency2
from .forms import NameForm


class GroupList(ListView):
    model = Group


class FunctionList(ListView):
    model = Function


class FeatureList(ListView):
    queryset = Feature.objects.select_related(u'function', u'function__group').all()


class DependencyList(ListView):
    queryset = Group.objects.prefetch_related('function','function__feature','function__feature__dependency')
    template_name = 'fmm/dependency_list.html'

class GroupFunctionList(ListView):
    template_name = u'fmm/function_by_group.html'
    context_object_name = u'group'

    def get_queryset(self):
        self.group_number = get_object_or_404(Group, pk=int(self.kwargs[u'group_number']))
        return Function.objects.filter(group=self.group_number)

    def get_context_data(self, **kwargs):
        context = super(GroupFunctionList, self).get_context_data(**kwargs)
        context[u'group_name'] = Group.objects.get(pk=int(self.kwargs[u'group_number']))
        return context


class FunctionFeatureList(ListView):
    template_name = u'fmmgui/feature_by_function.html'
    context_object_name = u'function'

    def get_queryset(self):
        self.group_pk = int(self.kwargs[u'group_number'])
        self.function_pk = int(self.kwargs[u'function_number'])
        return Feature.objects.filter(function=self.function_pk)

    def get_context_data(self, **kwargs):
        context = super(FunctionFeatureList, self).get_context_data(**kwargs)
        group_name = Group.objects.get(pk=self.group_pk).name
        function_name = Function.objects.get(pk=self.function_pk).name
        context[u'group_name'] = group_name
        context[u'function_name'] = function_name
        return context


def detail(request, feature_id):
    return HttpResponse(u"You're looking at feature %s." % feature_id)


def index(request):
    return HttpResponse(u"You're looking at fmmgui home page.")


# =============================================================================

def fmm_main(request, group_number):
    if Group.objects.filter(pk=group_number).count() > 0:
        group = Group.objects.get(pk=group_number)
        group_name = group.name
        group_list = list(Group.objects.order_by('name'))
    else:
        group_name = "Group_Not_Found"
        return HttpResponse(u"/fmm/fmm_main/%s" % group_name)

    template = 'fmm/fmm_main.html'
    feature_list = feature_list = Feature.objects.filter(function__group__pk=group_number)

    context = {'group_name': group_name, 'group_list': group_list, 'feature_list': feature_list}
    return render(request, template, context)


def fmm_main_index(request):
    groups = Group.objects.order_by('name')
    first_group = str(groups[0].pk)
    return HttpResponseRedirect(u"/fmm/fmm_main/%s" % first_group)

# =============================================================================


def loadfmm_old(request):
    fmm = open(u'FMM.txt', u'r')
    line_count = 0
    if Group.objects.count() > 0:
        Group.objects.all().delete()
    for line in fmm:
        line_data = line.rstrip().split(u',')
        group_name = line_data[0]
        function_name = line_data[1]
        feature_name = line_data[2]
        selection_name = line_data[3]
        dependencies = line_data[4].split(u';')
        rule_type = line_data[5]
        option_min = line_data[6]
        option_max = line_data[7]
        groups = Group.objects.filter(name=group_name)
        if not groups.exists():
            group = Group(name=group_name)
            group.save()
        group = Group.objects.get(name=group_name)
        functions = Function.objects.filter(name=function_name, group__name=group_name)
        if not functions.exists():
            function = group.function_set.create(name=function_name)
            function.save()
        function = Function.objects.get(name=function_name, group__name=group_name)
        features = Feature.objects.filter(name=feature_name, function__name=function_name, function__group__name=group_name)
        if not features.exists():
            feature = function.feature_set.create(name=feature_name)
            feature.selection_name = selection_name
            feature.rule_type = rule_type
            feature.option_min = option_min
            feature.option_max = option_max
            feature.save()
        feature = Feature.objects.get(name=feature_name, function__name=function_name, function__group__name=group_name)
        for dependency in dependencies:

            feature.dependency_set.create(name=dependency)

        feature.save()
        line_count += 1
        print "lines processed:", line_count

    response_text = u'FMM.txt load complete. ' + str(line_count) + u' records Processed. '
    return HttpResponse(response_text)


def get_name(request):
    print "get_name: request_method", request.method
    if request.method == 'POST':
        form = NameForm(request.POST)
        print "form is valid?", form.is_valid()
        if form.is_valid():
            return HttpResponseRedirect('/fmm/yourname/')
    else:
        form = NameForm()

    return render(request, 'name.html',{'form': form})


def test(request):
    print "test view"
    return render(request, 'fmm/test.html/', {})

# =============================================================================
# Need to fix problem of grabbing features with same names.  I think that is why the linking sometimes does not work.
def edit_feature(request, feature_number):
    template = 'fmm/feature_detail.html'
    feature = Feature.objects.get(pk=feature_number)
    dependency_list =  Dependency.objects.filter(feature__pk=feature_number)
    print "view: edit_feature, feature:", feature, feature.pk, "; dependencies: ", dependency_list
    if dependency_list.count >0:
        for d in dependency_list:
            print "dependency: ", d.pk, d.name
    context = {'feature': feature, 'dependency_list':dependency_list}
    return render(request, template, context)

# =============================================================================
class TestFeatureList2(ListView):
    model = TestFeature


def loadfmm(request):
    fmm = open(u'FMM.txt', u'r')
    line_count = 0
    print "lfmm: ", TestFeature2.objects.count()
    if TestFeature2.objects.count() > 0:
        TestFeature2.objects.all().delete()
    print "lfmm: ", TestFeature2.objects.count()
    for line in fmm:
        # 0-Group, 1-Function, 2-Feature_Name, 3-Feature, 4-Dependency, 5-Rule, 6-Min, 7-Max

        # group = models.CharField(max_length=50, blank=True)
        # function = models.CharField(max_length=50, blank=True)
        # feature_name = models.CharField(max_length=100, blank=True)
        # name = models.CharField(max_length=50, blank=True)  # keyword or feature
        # rule_type = models.CharField(max_length=15, blank=True, choices=RULE_TYPES)
        # option_min = models.IntegerField(blank=True, null=True)
        # option_max = models.IntegerField(blank=True, null=True)
        # enabled = models.NullBooleanField(default=False)
        # selected = models.NullBooleanField(default=False)

        line_data = line.rstrip().split(u',')
        group_name = line_data[0]
        function_name = line_data[1]
        feature_name = line_data[2]
        feature = line_data[3] # 'name' in the model
        dependencies = line_data[4].split(u';')
        rule_type = line_data[5]
        option_min = line_data[6]
        option_max = line_data[7]

        t = TestFeature2(
            group=group_name,
            function=function_name,
            feature_name=feature_name,
            name=feature,
            rule_type=rule_type,
            option_min=option_min,
            option_max=option_max
          )
        t.save()

        for dependency in dependencies:
            d = t.testdependency2_set.create(name=dependency)
            print "parent = ", t.name, " child = ", d.name





        dependency = dependencies

        line_count += 1
        print "lines processed:", line_count

    response_text = u'FMM.txt load complete. ' + str(line_count) + u' records Processed. '
    return HttpResponse(response_text)


#=======================================================================

def loadfmm_old2(request):
    fmm = open(u'FMM.txt', u'r')
    line_count = 0
    print "lfmm: ", TestFeature.objects.count()
    if TestFeature.objects.count() > 0:
        TestFeature.objects.all().delete()
    print "lfmm: ", TestFeature.objects.count()
    for line in fmm:
        # 0-Group, 1-Function, 2-Feature_Name, 3-Feature, 4-Dependency, 5-Rule, 6-Min, 7-Max

        # group = models.CharField(max_length=50, blank=True)
        # function = models.CharField(max_length=50, blank=True)
        # feature_name = models.CharField(max_length=100, blank=True)
        # name = models.CharField(max_length=50, blank=True)  # keyword or feature
        # dependency = models.ManyToManyField("self", symmetrical=False)
        # rule_type = models.CharField(max_length=15, blank=True, choices=RULE_TYPES)
        # option_min = models.IntegerField(blank=True, null=True)
        # option_max = models.IntegerField(blank=True, null=True)
        # enabled = models.NullBooleanField(default=False)
        # selected = models.NullBooleanField(default=False)

        line_data = line.rstrip().split(u',')
        group_name = line_data[0]
        function_name = line_data[1]
        feature_name = line_data[2]
        feature = line_data[3] # 'name' in the model
        dependencies = line_data[4].split(u';')
        rule_type = line_data[5]
        option_min = line_data[6]
        option_max = line_data[7]

fmmdemo/fmm/templates/fmm/base.html
{% load bootstrap3 %}
{% load bootstrap_themes %}
{% bootstrap_styles theme='simplex' type='css' %}

<!DOCTYPE html>
<html lang="en">
<html>
    <head>
        <title>PCC TEST PAGE</title>
    </head>
    <body>
            {% block content %}
            {% endblock %}
    </body>
</html>

fmmdemo/fmm/templates/fmm/dependency_list.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Feature by Function</title>
    </head>
    <body>
        {% block content %}
            <h2>Feature Model Master</h2>
            <table>
                <tr>
                    <th>Group</th>
                    <th>Function</th>
                    <th>Feature</th>
                    <th>Dependency</th>
                </tr>
                {% for dependency in object_list %}
                <tr>
                    <td>{{ name }}</td>
                    <td>{{ function.name }}</td>
                    <td>{{ function.feature.name }}</td>
                    <td>{{ function.feature.dependency.name }}</td>
                </tr>
                {% endfor %}
            </table>
        {% endblock %}
    </body>
</html>

fmmdemo/fmm/templates/fmm/feature_by_function.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Feature by Function</title>
    </head>
    <body>
        {% block content %}
            <h2> {{ group_name }} : {{ function_name }}</h2>
            <table>
                <tr>
                    <th>Group</th>
                    <th>Function</th>
                    <th>Feature</th>
                </tr>
                {% for feature in object_list %}
                <tr>
                    <td>{{ feature.function.group.name }} Gr</td>
                    <td>{{ feature.function.name }} Fu</td>
                    <td>{{ feature.name }} Fe</td>
                </tr>
                {% endfor %}
            </table>
        {% endblock %}
    </body>
</html>

fmmdemo/fmm/templates/fmm/feature_detail.html
<h2>{{ feature.name }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'fmm:edit_feature' feature.id %}" method="get">
{% csrf_token %}

<form>
    <fieldset id="group1"> Enabled <br>
        <input type="radio" value="Yes" name="Yes">Yes<br>
        <input type="radio" value="No" name="No">No<br>
    </fieldset>

    <fieldset id="group2">Selected <br>
        <input type="radio" value="Yes" name="Yes">Yes<br>
        <input type="radio" value="No" name="No">No<br>
    </fieldset>
</form>



<input type="submit" value="OK" />
</form>


<h4 align="center">Dependencies</h4>
<table align="center" class="table table-hover">
    <thead>
        <tr scope="col">
            <th scope="col">Dependent Feature</th>
        </tr>
    </thead>
    <tbody>
        {% for dependency in dependency_list %}
            <tr class="table-success">
                <td>{{ dependency.name }}</td>
                <td><a href="/fmm/feature/{{dependency.pk}}" class="btn btn-info" role="button">Edit</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

fmmdemo/fmm/templates/fmm/feature_form.html
<form action="{% url 'fmm:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Enter" />
</form>

<form action="/fmm/yourname/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

fmmdemo/fmm/templates/fmm/feature_list.html
{% extends 'fmm/base.html' %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Feature by Function</title>
    </head>
    <body>
        {% block content %}
            <h2>Feature Model Master</h2>
            <table class="table table-hover">
                <tr>
                    <th>Group</th>
                    <th>Function</th>
                    <th>Feature</th>
                    <th>Selected</th>
                </tr>
                {% for feature in object_list %}
                <tr class="table-success">
                    <td>{{ feature.function.group.name }}</td>
                    <td>{{ feature.function.name }}</td>
                    <td>{{ feature.name }}</td>
                    <td>{{ feature.selected }}</td>
                </tr>
                {% endfor %}
            </table>
        {% endblock %}
    </body>
</html>

fmmdemo/fmm/templates/fmm/fmm_main.html
{% extends 'fmm/base.html' %}
{% block content %}

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
               <a class="navbar-brand" href="#">PCC FMMGui</a>
            </div>
            <ul class="nav navbar-nav">
                {% for group in group_list %}
                    <li><a href='/fmm/fmm_main/{{ group.pk }}'>{{ group.name }}</a></li>
                {% endfor %}
                </ul>
        </div>
    </nav>

    <h4 align="center">Group: {{group_name}}</h4>
    <table class="table table-hover">
        <thead>
            <tr scope="col">
                <th scope="col">Function</th>
                <th scope="col">Feature</th>
                <th scope="col">Keyword</th>
                <th scope="col">Selected</th>
                <th scope="col">Enabled</th>
                <th scope="col">Edit</th>
            </tr>
        </thead>
        <tbody>
            {% for function in feature_list %}
                <tr class="table-success">
                    <td>{{ function.function.name }}</td>
                    <td>{{ function.name }}</td>
                    <td>{{ function.selection_name }}</td>
                    <td>{{ function.selected }}</td>
                    <td>{{ function.enabled }}</td>
                    <td><a href="/fmm/feature/{{function.pk}}" class="btn btn-info" role="button">Edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

fmmdemo/fmm/templates/fmm/function_by_group.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Function by Group</title>
</head>
<body>

</body>
</html>

fmmdemo/fmm/templates/fmm/function_list.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Functions</title>

    {% block content %}
        <h2>Functions</h2>
        <ul>
            {% for function in object_list %}
                <li>{{ function.name }}</li>
            {% endfor %}
        </ul>
    {% endblock %}


</head>
<body>

</body>
</html>

fmmdemo/fmm/templates/fmm/group_list.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group</title>

    {% block content %}
        <h2>Feature Groups</h2>
        <ul>
            {% for group in object_list %}
                <li>{{ group.name }}</li>
            {% endfor %}
        </ul>
    {% endblock %}


</head>
<body>

</body>
</html>

fmmdemo/fmm/templates/fmm/test.html
{% extends 'fmm/base.html' %}

{% block content %}
    <div>
        <h1><a href="/">PCC Test Page</a></h1>
    </div>

    <div>
        <p>published: 14.06.2014, 12:14</p>
        <h2><a href="">My first post</a></h2>
        <p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
    </div>

    <div>
        <p>published: 14.06.2014, 12:14</p>
        <h2><a href="">My second post</a></h2>
        <p>Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut f.</p>
    </div>
{% endblock %}

fmmdemo/fmm/templates/fmm/testfeature_list.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>All Features</title>
    </head>
    <body>
        {% block content %}
            <h2> All Features</h2>
            <table>
                <tr>
                    <th>Group</th>
                    <th>Function</th>
                    <th>Feature</th>
                    <th>Keyword</th>
                    <th>Dependencies</th>
                </tr>
                {% for feature in object_list %}
                <tr>
                    <td>{{ feature.group }} </td>
                    <td>{{ feature.function}} </td>
                    <td>{{ feature.feature_name }} </td>
                    <td>{{ feature.name }} </td>
                    <td> {% for dep in feature.dependency %}
                         {{ dep}}
                         {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% endblock %}
    </body>
</html>

fmmdemo/fmm/templates/fmm/testfeaturelist2_list.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>All Features Rick</title>
    </head>
    <body>
        {% block content %}
            <h2> All Features</h2>
            <table>
                <tr>
                    <th>Group</th>
                    <th>Function</th>
                    <th>Feature</th>
                    <th>Keyword</th>
                    <th>Dependencies</th>
                </tr>
                {% for feature in object_list %}
                <tr>
                    <td>{{ feature.group }} </td>
                    <td>{{ feature.function}} </td>
                    <td>{{ feature.feature_name }} </td>
                    <td>{{ feature.name }} </td>
                    <td> {% for dep in feature.dependency %}
                         {{ dep}}
                         {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        {% endblock %}
    </body>
</html>